### ISSUE TITLE
Examples are out of link

### ISSUE THREAD

**Issue by sotetsuk** [passive-radio/pigframe#1]
These links are out of link

<img width="1077" alt="image" src="https://github.com/passive-radio/pigframe/assets/5868442/05b9e62c-bb1d-415e-8de9-1356d75da728">

Like this

<img width="1094" alt="image" src="https://github.com/passive-radio/pigframe/assets/5868442/d40abc96-4bab-4b7e-b1b3-8e691742fad3">

**Comment by passive-radio** [comment]
@sotetsuk 
Thanks!
Fixed with commit 21ffd5674fd3088d31755ac7f7bdfe8d03f1b4d6
